server:
  port: 7777

spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    url: jdbc:mysql://8.130.173.216:3306/myBlog?characterEncoding=utf8&serverTimezone=Asia/Shanghai
    hikari:
      username: ChenYujie
      password: Cheng125835+-
      driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 8.130.173.216
    port: 6379
    password: Cheng125835
mybatis:
  mapper-locations:
    - classpath*:mapper/*.xml
  type-aliases-package: cdu.cyj.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
pagehelper:
  reasonable: true
oss:
  accessKey: dhHUdry64TNgJTOxeR1uYndKoNYmZ7YlxsNiCZUd
  secretKey: wBJdWuMEeJT3rXV-F3GNTJiFPzmOyX5JbeOWOKtB
  bucket: myblogoss
  domain: http://rfxgxvtms.hn-bkt.clouddn.com/

