server:
  port: 7777

spring:
  datasource:
    url: jdbc:mysql://8.130.173.216:3306/myBlog?characterEncoding=utf8&serverTimezone=Asia/Shanghai
    hikari:
      username: ChenYujie
      password: Cheng125835+-
      driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  mapper-locations:
    - classpath*:mapper/*.xml
  type-aliases-package: cdu.cyj.entity
pagehelper:
  reasonable: true

